### PR TITLE
Build fixes Docker image

### PR DESCRIPTION
**Pull request by lkuchenb**

### CODE REVIEW

**Comment by christopher-mohr** [comment]
Curl download seems to work now however not it fails because of Cython...

> Traceback (most recent call last):
>   File "<string>", line 17, in <module>
>   File "/tmp/pip_build_root/tables/setup.py", line 756, in <module>
>     cython_extfiles = get_cython_extfiles(cython_extnames)
>   File "/tmp/pip_build_root/tables/setup.py", line 749, in get_cython_extfiles
>     from Cython.Build import cythonize
> ImportError: No module named Cython.Build

**Comment by b-schubert** [comment]
I belief the error comes from a missing library:

```/usr/bin/ld: cannot find -llzo```

which is provided by the:

```zlib1g-dev package```

**Comment by lkuchenb** [comment]
OK, seems to build now. Don't merge this yet, I would still fix the versions of all python package deps. I guess newer versions of those packages being installed breaks the build every now and then...

**Comment by b-schubert** [comment]
Okay Ill just wait for your go-ahead!

**Comment by lkuchenb** [comment]
OK, I fixed the versions of the pip installed python packages and removed cython and matplotlib - these are now obtained solely from the Ubuntu repository. @christopher-mohr @b-schubert Is that a problem? Version is obviously slightly older. If that's not an issue, I think this PR is good to go.

**Comment by b-schubert** [comment]
@lkuchenb Thanks a lot. I Think to figure out whether we can use the cython and matplotlib of ubuntu, it would be good to run the OptiType script. That should use functions of both packages.

**Comment by lkuchenb** [comment]
OK, I checked the package requirements on the OptiType page and moved matplotlib back to pip. We're now higher or equal with all python packages listed on the OptiType page.

**Comment by b-schubert** [comment]
great! Should I merge then?

**Comment by lkuchenb** [comment]
From my side, yes

**Pull request merged**
