### PR TITLE
dockerImage added

### PR DESCRIPTION
**Pull request by Leon-Bichmann**
Seems like I overlooked this small bug occuring in KNIME as well:

Execute failed: Docker-Node Variants2Proteins has no image defined

### CODE REVIEW

**Comment by Leon-Bichmann** [comment]
Any Ideas why travis is failing again? (Maybe @lkuchenb)

**Comment by b-schubert** [comment]
Nope, the previous PR all worked fine. lokal build fails as well according
to Chris. Perhaps new releases of some packages??

**Comment by christopher-mohr** [comment]
It always fails in the first curl command which doesn't make any sense since nothing has been changed since the last successful build. The curl command works if I test it locally. I also tested other options with curl but it didn't help...

Could you also please try to build the docker container locally @Leon-Bichmann @lkuchenb ?

**Comment by Leon-Bichmann** [comment]
Getting the following error:
curl: (23) Failed writing body (0 != 16132)

Stackoverflow responses:
https://stackoverflow.com/questions/16703647/why-curl-return-and-error-23-failed-writing-body

**Pull request merged**
