### PR TITLE
set ctd string parameter to bool

### PR DESCRIPTION
**Pull request by Leon-Bichmann**

### CODE REVIEW

**Comment by christopher-mohr** [comment]
Is this related to changes in KNIME? If so, we would have to update all CTD files I guess...

**Comment by b-schubert** [comment]
I don't know you have to ask the KNIME guys. This worked with the KNIME
version at the time of publication!

**Comment by Leon-Bichmann** [comment]
Yeah, seems like this is the case at least in my knime installation..  (@jpfeuffer)

I dont know if you saw the error message I posted in the previous pull request:
```
ERROR NeoEpitopePredicton  0:180      Failing process stdout: []
ERROR NeoEpitopePredicton  0:180      Failing process stderr: [usage: neoepitopeprediction.py [-h],                                [-m {netmhcstabpan,smmpmbec,syfpeithi,netmhc,netctlpan,smm,tepitopepan,netmhcii,arb,pickpocket,epidemix,unitope,netmhciipan,comblibsidney,netmhcpan,calisimm,hammer,svmhc,bimas}],                                [-v VCF] [-t {VEP,ANNOVAR,SNPEFF}],                                [-p PROTEINS],                                [-l {8,9,10,11,12,13,14,15,16,17}] -a ALLELES,                                [-r REFERENCE] [-fINDEL] [-fFS] [-fSNP] -o,                                OUTPUT,
neoepitopeprediction.py: error: unrecognized arguments:  true]
ERROR NeoEpitopePredicton  0:180      Execute failed: Failed to execute node NeoEpitopePredicton
```

Can we maybe test it with this pull request and if it works update the other nodes?

**Comment by christopher-mohr** [comment]
There seems to be a difference between PARAMETERS version 1.6.2 and version 1.7 in the CTD schema with respect to boolean parameters but that has been changed in 2016. CTDs in Immunonodes use version 1.6.2, GKN use 1.7...

**Comment by jpfeuffer** [comment]
I'm confused now. In GKN *currently* we expect Strings with true/false apparently.
https://github.com/genericworkflownodes/GenericKnimeNodes/blob/d6fb58ac6d190262f3c60c3f271a8dbbc2d77cdf/com.genericworkflownodes.knime.config/src/com/genericworkflownodes/knime/config/reader/handler/ParamHandler.java#L505
I don't know which ParamXML version this corresponds to.
Are you sure that this specific node worked before? It seems like your python command line does only accept flags (which seems like we do not support at all in GKN).
I don't know what version of GKN you use in Immunonodes though.
Let's summon @chahuistle to the party.

**Comment by jpfeuffer** [comment]
E.g. https://github.com/FRED-2/ImmunoNodes/blob/master/src/neoepitopeprediction.py#L188
Why is this not string or bool? Was the CTD generated with CTDopts or was it written manually?

**Comment by b-schubert** [comment]
Uf I honestly can't remember..... I finished that project over two years
ago...

**Comment by chahuistle** [comment]
AFAIK CTDopts still uses the old CTD version which doesn't support `bool`, so I will release a version implementing this feature and upload it to the conda cloud.

See: https://github.com/WorkflowConversion/CTDopts/issues/18

(I maintain https://github.com/WorkflowConversion/CTDopts and https://github.com/WorkflowConversion/CTDSchema)

**Comment by jpfeuffer** [comment]
I will do the same for GKN. For now you could try using strings of course.

**Comment by Leon-Bichmann** [comment]
Hey guys whats the status on this? When do you think this will be fixed?

Otherwise I can change it to string for now.

Would be great to have it running by september.

**Comment by chahuistle** [comment]
@Leon-Bichmann I just need to find the time to implement this on my end, but it will certainly be done by September. 

Also, pull-requests are welcome ;)

**Comment by jpfeuffer** [comment]
https://github.com/genericworkflownodes/GenericKnimeNodes/pull/212
Tested on the wget example from the CTD Schema docu.

**Comment by chahuistle** [comment]
I had a look at CTDopts and, If I recall correctly, it was used once to generate the CTDs that in turn are parsed by GKN's `node_generator` (this happens in the ImmunoNodes nightly build).

Running the following script works, meaning, CTDopts already supported the use of `bool` parameters. My previous comment was incorrect. Sorry about that.

```python
#!/usr/bin/env python

from CTDopts.CTDopts import CTDModel

wget = CTDModel(from_file="wget.ctd")
params = wget.list_parameters()

values = {
'outputDocument': '/tmp/allele_frequency.py',
'noCertificate': True,
'noVerbose': False,
'url': 'https://raw.githubusercontent.com/FRED-2/ImmunoNodes/master/src/allelefrequency.py'
}

validated = wget.validate_args(values)

wget.write_ctd('/tmp/generated_wget.ctd', validated)
```

**Comment by Leon-Bichmann** [comment]
Thanks for the help, can we merge this?

**Comment by jpfeuffer** [comment]
Looks reasonable to me.

**Pull request merged**
