### PR TITLE
Feature/vcf to fasts

### PR DESCRIPTION
**Pull request by Leon-Bichmann**
very preliminary first version

code was adapted from neoeptiopeprediction.py

### CODE REVIEW

**Comment by Leon-Bichmann** [comment]
It would be great to consider variants that fall into non-coding reading frames as well.. if u have a solution for this

**Comment by b-schubert** [comment]
Code looks good. generate_transcripts_from_vcf might take a while if you have a lot of variants per transcript and no zygosity information since it generates all 2**nof_herterozygous_variants transcripts (which is the default).

If you want to generate proteins in alternative reading frames you essentially have to overwrite the translate function in Fred2's Transcript-object (http://seqanswers.com/forums/showthread.php?t=49487). Transcripts, Proteins, and Peptides are subclasses of Biopython.Seq.

Or do you mean synonymous mutations?

Have you checked the Travis error?

**Comment by Leon-Bichmann** [comment]
Thanks for your response!

Unforunatly, Im not sure about the travis error. 

Ok, alternative reading frames seems straight forward.
How about variants that are from non-coding genomic areas (https://www.nature.com/articles/ncomms10238). Is there anyway to incorporate these as well?

**Comment by b-schubert** [comment]
Non-coding regions is a bit harder. You need to essentially extract the reference genome and impute the variants according to their genomic positions instead of their transcript positions (as it is done right now). 

Once you have that, you have to decide from where to start the transcription/translation. If you only consider SNV, than you can just generate all k-mer windows surrounding the mutation(s) (see generate_peptides_from_variants as example). When considering INDELs, you also have to track the positional shift for each following mutation.

in order to do that you need to:

1) Extend the MartAdapter to extract a region of a reference genome 
2) write a new generator function for non-coding regions

**Comment by Leon-Bichmann** [comment]
Ok seems a bit complicated, ill have a look if Ill be able to implement this in a later pull request.

Do you see why travis is failing? Not sure whats the problem.

**Comment by Leon-Bichmann** [comment]
When I generated a vcf using Variant Effect Predictor via their webinterface I got a vcf with a lot more info columns than you specified in the vcf_reader function.

If you agree I would adapt the vcf_reader as well in the neoepitopeprediction.py

screen shot 2018-07-06 at 16 05 32

**Comment by b-schubert** [comment]
Sure. Is the stand-alone version producing the same output?

**Comment by Leon-Bichmann** [comment]
I havent tried the standalone, usually I use SnpEff. But im installing it right now.

Using the Fred.IO.vcf_reader it is actually possible to read in SnpEff vcfs as well - added it as well.

**Comment by Leon-Bichmann** [comment]
Ok testet the standalone as well. The same format is produced by it.

**Pull request merged**
